Repository Team-Ampersand/GYMI-Backend, pull requests merged in 2023-08, with the labels that each got.

#16 db dependencies 교체
  build.gradle.kts
Labels: 2️⃣ Priortiy: Medium, ⚙ Type: Setting, 🌏 Type: Deploy

#18 s3를 사용한 이미지 업로드 서비스 구현
  build.gradle.kts
  src/main/kotlin/com/example/gymi/domain/file/exception/FileUploadFailedException.kt
  src/main/kotlin/com/example/gymi/domain/file/exception/InvalidFormatFileException.kt
  src/main/kotlin/com/example/gymi/domain/file/service/FileService.kt
  src/main/kotlin/com/example/gymi/domain/file/service/impl/FileServiceImpl.kt
  src/main/kotlin/com/example/gymi/global/config/s3/S3Config.kt
  src/main/kotlin/com/example/gymi/global/error/exception/ErrorCode.kt
  src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ⚙ Type: Setting, ✨ Type: Feature

#26 공지글 수정 api 구현
  src/main/kotlin/com/example/gymi/domain/notice/entity/Notice.kt
  src/main/kotlin/com/example/gymi/domain/notice/entity/NoticeFile.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/NoticeController.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/data/dto/EditNoticeDto.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/data/request/EditNoticeRequestDto.kt
  src/main/kotlin/com/example/gymi/domain/notice/service/EditNoticeService.kt
  src/main/kotlin/com/example/gymi/domain/notice/service/impl/EditNoticeServiceImpl.kt
  src/main/kotlin/com/example/gymi/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#30 🔀 :: 27 - 신고 엔티티 개발
  src/main/kotlin/com/example/gymi/domain/declaration/entity/Declaration.kt
  src/main/kotlin/com/example/gymi/domain/declaration/enums/DeclarationType.kt
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature

#29 공지글 리스트 api 구현
  src/main/kotlin/com/example/gymi/domain/notice/presentation/NoticeController.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/data/response/ListNoticeResponseDto.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/data/response/NoticeResponseDto.kt
  src/main/kotlin/com/example/gymi/domain/notice/repository/NoticeRepository.kt
  src/main/kotlin/com/example/gymi/domain/notice/service/ListNoticeService.kt
  src/main/kotlin/com/example/gymi/domain/notice/service/impl/ListNoticeServiceImpl.kt
  src/main/kotlin/com/example/gymi/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#32 공지글 상세보기 api 구현
  src/main/kotlin/com/example/gymi/domain/notice/presentation/NoticeController.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/data/dto/NoticeFileDto.kt
  src/main/kotlin/com/example/gymi/domain/notice/presentation/data/response/DetailNoticeResponseDto.kt
  src/main/kotlin/com/example/gymi/domain/notice/service/DetailNoticeService.kt
  src/main/kotlin/com/example/gymi/domain/notice/service/impl/DetailNoticeServiceImpl.kt
  src/main/kotlin/com/example/gymi/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#34 선생님 GAuth 계정 로그인 추가
  src/main/kotlin/com/example/gymi/domain/auth/service/impl/SignInServiceImpl.kt
  src/main/kotlin/com/example/gymi/domain/auth/util/AuthConverter.kt
  src/main/kotlin/com/example/gymi/domain/auth/util/AuthUtil.kt
  src/main/kotlin/com/example/gymi/domain/auth/util/impl/AuthConverterImpl.kt
  src/main/kotlin/com/example/gymi/domain/auth/util/impl/AuthUtilImpl.kt
  src/main/kotlin/com/example/gymi/domain/user/enums/Role.kt
  src/main/kotlin/com/example/gymi/global/security/jwt/TokenProvider.kt
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature
